### ISSUE TITLE
Builder - GtkSourceView invalid object type

### ISSUE THREAD

**Issue by achjaj** [afcowie/java-gnome#15]
I try run application using Glade and java give me this error:
`Exception in thread "main" java.text.ParseException: Invalid object type „GtkSourceView“ on line 255
	at org.gnome.gtk.Builder.addFromFile(Builder.java:107)
	at app.Main.main(Main.java:29)
	...
`
I have installed `java-gnome 4.1.3` and `libgtksourceview-3.0-dev 3.16-1`.

**Comment by rudolfschmidt** [comment]
is the project dead, I cannot build the project and that issues seem to be old and still open....

**Comment by albfan** [comment]
Yout need to register type before use on Builder. See this python example

https://stackoverflow.com/a/10528052/848072

**Comment by afcowie** [comment]
@rudolfschmidt perhaps not dead, but unfortunately not actively maintained by anyone. I'd be pleased to see that change, but I personally haven't been working in Java for a long time. If a new team of maintainers wants to adopt the package I would be fine with that.

**Comment by albfan** [comment]
@afcowie, I'm gnome foundation member and had been working on java-gnome. https://gitlab.gnome.org/albfan/java-gnome. I want to revamp work on auto gir parsing (so there's no manual work to keep in sync with upstream) Busy with vala these days (I'm gitg maintainer) but definitely there's someone working on java for gtk

**Comment by rudolfschmidt** [comment]
I am Java developer, is there a way I can support or help with the gtk bindings? I have started to map ncurses with java, was even able to build some basic ncurses apps: https://github.com/rudolfschmidt/jcurses

**Comment by albfan** [comment]
@rudolfschmidt of course you can. See https://gitlab.gnome.org/albfan/java-gnome/issues

java-gnome just works, is only it maps widgets manually and we want to do it parsing GIR files so new widgets are automatically avaliable https://gitlab.gnome.org/albfan/java-gnome/issues/5. 

Once that is done we need more tutorials https://gitlab.gnome.org/albfan/java-gnome/issues/2 and the would be great to port buildsystem to meson https://gitlab.gnome.org/albfan/java-gnome/issues/3 fix test suite https://gitlab.gnome.org/albfan/java-gnome/issues/1.

You can reach us on IRC gimpnet java-gnome or https://riot.im/app/#/room/#_gimpnet_#java-gnome:matrix.org matrix bridge, just say hi and we can get into details
