### ISSUE TITLE
Gtk.init(String[]) line 95 ErrorInInitializerError

### ISSUE THREAD

**Issue by a-piece-of-garbage** [afcowie/java-gnome#23]
Was writing something when I got the following output:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.gnome.gtk.Gtk.init(Gtk.java:95)
	at GtkTest.main(GtkTest.java:5)
Caused by: java.lang.NullPointerException
	at org.freedesktop.bindings.Plumbing.loadNativeCode(Plumbing.java:192)
	at org.freedesktop.bindings.Plumbing.<clinit>(Plumbing.java:110)
	... 2 more
```
Wrote something with the following code with the same output:
```
import org.gnome.gtk.Gtk;
public class GtkTest {
	public static void main(String[] args) {
		Gtk.init(args);
	}
}
```
I have no idea what is happening, but will gladly post more information on request.

**Comment by afcowie** [comment]
No idea, really, but just guessing, maybe your `LD_LIBRARY_PATH` is wrong, somehow? I seem to recall jumping through a lot of hoops to make sure that the program could find _libgtkjni-4.1.4-dev.so_ or whatever. Did you set `--prefix` when calling _./configure_?

**Comment by a-piece-of-garbage** [comment]
I installed from the `.deb` package, so I didn't do any of those things.
